# Sprint 9
ZherebtsovAA/java-filmorate pull request #6
Opened 2023-04-06 07:28 UTC by ZherebtsovAA

2023-04-06 20:18 UTC, ohelly requested changes
Привет! В целом отличная работа, прекрасный код. Есть несколько замечаний, которые необходимо исправить. Также я оставил ряд рекомендаций, на которые стоит обратить внимание.
В случае возникновения вопросов, можно обращаться ко мне в пачку.

2023-04-06 20:18 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Past
Рекомендация: Также считаю, что валидация даты релиза с использованием Past лишняя, так как могут добавить фильм, который еще только выйдет.

2023-04-06 20:18 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController() {
Рекомендация: В данном случае можно избавиться от конструктора, так как он всегда задает одни и те же значения. Конструктор в основном используют только тогда, когда в него приходят параметры, например если бы он принимал стартовое значение для поля id. В данном случае достаточно такого:
![image](https://user-images.githubusercontent.com/51891976/230482943-6d2eecda-3757-47cc-b5e3-25094faeb255.png)

2023-04-06 20:18 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final List<FilmValidator> filmValidators = List.of(new FilmNameValidator(), new FilmDescriptionValidator(), new FilmReleaseDateValidator(), new FilmDurationValidator());
А почему используется ручная валидация, если в методах уже есть аннотация ``@Valid``? Не осуждаю такой вариант, тем более учитывая то, что он отлично написан, просто интересно, почему используется оба варинта?

2023-04-06 20:18 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            films.put(id++, film);
Рекомендация: Для инкремента идентификатора рекомендую использовать данный вариант
![image](https://user-images.githubusercontent.com/51891976/230483495-5bd7dd91-e261-4c2e-a454-ff577697af01.png)
Потому что между строкой 35 и 36 он может измениться параллельным запросом.

2023-04-06 20:18 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.warn("Фильма с ID: '" + film.getId() + "' нет в списке фильмов");
Рекмоендация: В данном случае рекомендую просто вручную выкидывать какой нибудь NotFoundException.

2023-04-06 20:18 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Получен запрос к эндпоинту: '{} {}', Строка параметров запроса: '{}', Фильм: '{}'", request.getMethod(), request.getRequestURI(), request.getQueryString(), film);
Необходимо исправить: В методе добавления происходит валдиция входящего фильма, а в данном случае нет. Конечно она отработает из-за аннотации ``@Valid``, но почему тогда есть ручная проверка в методе добавления?)
Но в данном случае замечание связано с тем, что отстутсвует валидация даты рализа фильма(при добавлении это происходит вручную)

2023-04-06 20:18 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        } catch (ValidateFilmNameException exception) {
Рекомендация: Также рекомендую не выстраивать логику на исключениях, так как это довольно ресурснозатратно. Можно сделать всего лишь одно исключение, ValidationException, с полем message и использовать его для всех случаев. Пример:
![image](https://user-images.githubusercontent.com/51891976/230484615-84af68b0-9803-4d27-b79b-fe4dcf815514.png)
Валидатор:
![image](https://user-images.githubusercontent.com/51891976/230484669-d6def3b2-0464-4280-8d03-b9b25fbaab7b.png)
Также, исключение вообще можно не отлавливать, сделав его RuntimeException и просто выкидывать при ошибке:
![image](https://user-images.githubusercontent.com/51891976/230484863-ddf773f2-f583-4bc6-b999-07a8f4608d17.png)
![image](https://user-images.githubusercontent.com/51891976/230484930-82e4c0f1-72cf-4d32-a7ea-30d400b4b31f.png)
Вернется ошибка со статусом 500, в случае ошибки, а если все хорошо, то просто вернется фильм со статусом 200

2023-04-06 20:18 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
В целом для данного класса также применятся все замечания и рекомендации из класса FilmController.

2023-04-07 03:53 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int id;
Изменения внесены в классы Film, User.

2023-04-07 04:07 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Past
Аннотация @Past для поля releaseDate удалена.

2023-04-07 04:14 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController() {
Удалены конструкторы: FilmController(), UserController(). Нужные поля сразу инициализированы.

2023-04-07 04:25 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            films.put(id++, film);
Инкрементация идентификатора исправлена для классов: FilmController(), UserController().

2023-04-07 05:17 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.warn("Фильма с ID: '" + film.getId() + "' нет в списке фильмов");
Исправлено для классов: FilmController(), UserController().

2023-04-07 05:52 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        } catch (ValidateFilmNameException exception) {
Оставлено исключение ValidationException(), наследует RuntimeException(). Лишние исключения удалены. Внесены изменения в валидаторы.

2023-04-07 06:10 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final List<FilmValidator> filmValidators = List.of(new FilmNameValidator(), new FilmDescriptionValidator(), new FilmReleaseDateValidator(), new FilmDurationValidator());
Про валидацию аннотациями написано в самом конце ТЗ и на усмотрение обучающегося. Поэтому когда уже были написаны валидаторы, исключения жалко было удалять. Хотя я понимал, что нужно оставить что-то одно, либо использовать не все валидаторы, а часть, случаи, которые не покрываются аннотациями.  Так же в целях обучения, было интересно посмотреть как поведут себя ручные валидаторы с аннотациями. Сейчас понимаю, что одно другому не мешает. Но смысла нет в ручном валидаторе, если он покрывается аннотацией. Тем более изучаем Spring. Надо пользоваться аннотациями. Получил обратную связь, за что большое спасибо! Теперь больше понимая в голове. Лишние валидаторы удаляю.

2023-04-07 08:27 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Получен запрос к эндпоинту: '{} {}', Строка параметров запроса: '{}', Фильм: '{}'", request.getMethod(), request.getRequestURI(), request.getQueryString(), film);
Исправлено. Создана кастомная аннотация @ValidReleaseDate для поля releaseDate.

2023-04-07 08:30 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
Исправления согласно рекомендаций внесены в класс UserController. 
Благодарю за замечания, код стал точно лучше, я научился новому!

2023-04-07 15:02 UTC, ohelly approved these changes
Привет! Все супер, исправлены все замечания. Можно двигаться дальше, работу принимаю. Удачи в дальнейшем обучении!

2023-04-07 15:02 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/validators/ValidReleaseDateValidator.java
> +        return releaseDate.isAfter(birthdayCinema);
Рекомендация: Рекомендую добавить проверку на то, что releaseDate != null, так как аннотация над полем(``@NotNull``) необязательно сработает первая. Если не проверять на != null здесь, то может выпасть ``NulPointerException``

2023-04-08 07:03 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/validators/ValidReleaseDateValidator.java
> +        return releaseDate.isAfter(birthdayCinema);
Проверка добавлена.

2023-04-17 16:34 UTC, merged