Доработка ТЗ9 до ТЗ10
ZherebtsovAA/java-filmorate pull request #7
Opened 2023-04-17 16:31 UTC by ZherebtsovAA

2023-04-18 16:26 UTC, ohelly requested changes
Привет! Отлично выполненая работа, прекрасный код. Есть несколько простых замечания, которые необходимо исправить. Также я оставил ряд рекомендаций, на которые стоит обратить внимание.
В случае возникновения вопросов можно обратиться ко мне в пачку.

2023-04-18 16:26 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        List<User> friend = userStorage.findUserById(new ArrayList<>(Collections.singletonList(friendId)));
Рекомендация: Преобразование в лист можно сократить следующим образом: ``List.of(userId);``

2023-04-18 16:26 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (friend.isEmpty()) {
Необходимо исправить: Проверяется на существование пользователь с идентификатором friendId, а пользователь с userId не проверяется. Для него тоже необходимо добавить проверку.

2023-04-18 16:26 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        List<User> friend = userStorage.findUserById(new ArrayList<>(Collections.singletonList(friendId)));
Рекомендация: Преобразование в лист можно сократить следующим образом: ``List.of(userId);``

2023-04-18 16:26 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public List<User> findCommonFriends(Integer userId, Integer otherId) {
Необходимо исправить: Данный метод работает не совсем верно, он находит всех уникальных друзей у первого и второго пользователя, но не общих. Например если взять такой пример: 
Список друзей у userId: ``[1, 2, 3, 4]``
Список дурзей у friendId: ``[1, 2, 3]``
То вернется: ``[1, 2, 3, 4]``

2023-04-18 16:26 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private static Integer globalFilmId = 1;
Рекомендация: Аналогичная рекомендая по выносу идентификаторов в логику хранилища.

2023-04-18 16:26 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        filmStorage.addLike(filmId, userId);
Необходимо исправить: Отсутствует проверка на существование фильма.

2023-04-18 16:26 UTC, ohelly commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	void contextLoads() {
Рекомендация: Рекомендую написать тестов для сервисов и хранилищ.

2023-04-20 15:59 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        return users.get(user.getId());
Исправлено: в классе InMemoryFilmStorage и InMemoryUserStorage.

2023-04-20 16:07 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(UserStorage userStorage) {
Исправлено: добавлена аннотация @RequiredArgsConstructor.

2023-04-20 16:10 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private static Integer globalUserId = 1;
Исправлено: перенесено в хранилище, внесены изменения.

2023-04-20 16:11 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        List<User> result = userStorage.findUserById(new ArrayList<>(Collections.singletonList(userId)));
Исправлено: метод переписан.

2023-04-20 16:12 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        List<User> friend = userStorage.findUserById(new ArrayList<>(Collections.singletonList(friendId)));
Исправлено: метод переписан.

2023-04-20 16:21 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        List<User> friend = userStorage.findUserById(new ArrayList<>(Collections.singletonList(friendId)));
Исправлено: метод findUserById переписан.

2023-04-20 16:22 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return userStorage.findUserById(new ArrayList<>(userStorage.getIdUserFriends(userId)));
Исправлено: метод findUserById переписан.

2023-04-20 16:30 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (friend.isEmpty()) {
Исправлено: если пользователь с userId, friendId не найден методом findUserById, выбрасывается исключение NotFoundException("пользователя с ID: " + ... + " нет в списке пользователей").

2023-04-20 16:39 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public List<User> findCommonFriends(Integer userId, Integer otherId) {
Исправлено: внесены изменения в логику работы метода.

2023-04-23 11:12 UTC, ZherebtsovAA commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	void contextLoads() {
Написаны тесты для проверки методов сервисов и хранилищ.

2023-04-23 11:13 UTC, ZherebtsovAA commented
Все замечания исправлены.
С богом!!!

2023-04-25 02:13 UTC, merged