feat: выполнить доработку проекта по ТЗ11
ZherebtsovAA/java-filmorate pull request #8
Opened 2023-05-02 18:21 UTC by ZherebtsovAA

2023-05-04 11:28 UTC, ohelly requested changes
Привет! Отличная работа, в целом все работает корректно. Есть одно небольшое замечание, которое необходимо исправить. Также я оставил ряд рекомендаций, на которые стоит обратить внимание.
В случае возникновения вопросов можно обратить ко мне в пачку.

2023-05-04 11:28 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/dao/film/FilmDbStorage.java
> +        if (filmId == null || filmId < 1 || isNotExists(filmId)) {
Рекомендация: Можно избавиться от лишнего запроса на проверку сущестсования фильма, который происходит в методе isNotExists. Для этого можно проверять, какое число возвращает метод update, он возвращает число строк, на которые повлиял запрос и если это число == 0, то такого фильма нет.

2023-05-04 11:28 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/dao/film/FilmDbStorage.java
> +        //noinspection ConstantConditions: наличие film проверено методом isNotExists(filmId)
Рекомендация: В данном случае тоже можно избавиться от лишнего запроса в isNotExists следующими способами:
1) Отловить ошибку:
![image](https://user-images.githubusercontent.com/51891976/236187007-70b5f70e-3dfd-43af-8995-ebe4f4883515.png)
2) или доставать список и проверять что в нем ровно один елемент:
![image](https://user-images.githubusercontent.com/51891976/236187186-b6692ba6-4527-4d09-8577-64501cdefb4e.png)

2023-05-04 11:28 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/dao/film/FilmDbStorage.java
> +            film.setGenres(filmGenreDb.findGenreByFilmId(film.getId()));
Необходимо исправить: Сейчас происходит N запросов для поиска жанров для N фильмов. Необходимо сделать так, чтобы поиск жанров осуществлялся одним запросом независимо от количества фильмов. Для этого поможет запрос в БД с оператором IN и HashMap.

2023-05-04 11:28 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/dao/user/UserDbStorage.java
> +        if (userId == null || userId < 1 || isNotExists(userId)) {
Рекомендация: Аналогичная рекомендация по избавлению от метода isNotExists, так как в репозитории фильмов.

2023-05-04 11:28 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/dao/user/UserDbStorage.java
> +            findUserById(id).ifPresent(friends::add);
Рекомендация: В данном случае тоже происходит много запросов из-за цикла. Данную операцию можно сделать одним запросом к БД с использованием оператор IN.

2023-05-04 11:28 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/dao/user/UserDbStorage.java
> +            findUserById(id).ifPresent(commonFriends::add);
Рекомендация: Аналогичная рекомендация по использованию запроса с оператором IN

2023-05-05 02:58 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/dao/MpaDb.java
> +                        .id(resultSet.getInt("MPA_ID"))
Исправлено.

2023-05-05 03:00 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/dao/GenreDb.java
> +                        .id(resultSet.getInt("GENRE_ID"))
Исправлено.

2023-05-05 05:04 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/dao/CustomerFriendDb.java
> +        int result = jdbcTemplate.queryForObject(
БД H2 (по ТЗ используем именно эту БД) не поддерживает подобную конструкцию. Пробовал разные версии H2, пробовал запускать в режиме совместимости по рекомендации из статьи: https://groups.google.com/g/h2-database/c/4PLdYAhz9ho/m/wXMtwRIFBgAJ. У меня не получилось выполнить команду с оператором "ON CONFLICT DO NOTHING". В PostgreSQL это отлично работает. Спасибо за рекомендацию!

2023-05-05 05:58 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmGenreDb.java
> +        for (Genre genre : genres) {
Реализовано одним запросом.

2023-05-05 06:36 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/dao/film/FilmDbStorage.java
> +        if (filmId == null || filmId < 1 || isNotExists(filmId)) {
Исправлено.

2023-05-05 06:45 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/dao/film/FilmDbStorage.java
> +        //noinspection ConstantConditions: наличие film проверено методом isNotExists(filmId)
Исправлено.

2023-05-05 06:52 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/dao/user/UserDbStorage.java
> +        if (userId == null || userId < 1 || isNotExists(userId)) {
Исправлено.

2023-05-05 18:55 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/dao/film/FilmDbStorage.java
> +            film.setGenres(filmGenreDb.findGenreByFilmId(film.getId()));
Исправлено.

2023-05-06 03:32 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> -@RequiredArgsConstructor
Изменения внесены.

2023-05-06 04:08 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/dao/user/UserDbStorage.java
> +            findUserById(id).ifPresent(friends::add);
Изменения внесены.

2023-05-06 04:31 UTC, ZherebtsovAA commented on src/main/java/ru/yandex/practicum/filmorate/dao/user/UserDbStorage.java
> +            findUserById(id).ifPresent(commonFriends::add);
Исправлено.

2023-05-06 18:11 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/dao/CustomerFriendDb.java
> +        int result = jdbcTemplate.queryForObject(
Можно использовать mode для H2, чтобы это заработало. Для этого в application.properties заменить строку ``spring.datasource.url=jdbc:h2:mem:testdb`` на ``spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL``

2023-05-06 18:15 UTC, ohelly approved these changes
Привет! Все супер, исправлены все замечания. Работу принимаю, можно двигаться дальше. Удачи в дальнейшем обучении!

2023-05-18 13:40 UTC, merged